### ISSUE TITLE
npm build fails with 'Error: Fallback bindings does not support this interface yet.'

### ISSUE THREAD

**Issue by mortilla** [darrylschaefer/ai-text-editor#1]
System information:
```
$ uname -a
Linux zbox 6.5.7-artix1-1 #1 SMP PREEMPT_DYNAMIC Sun, 15 Oct 2023 22:13:26 +0000 x86_64 GNU/Linux
```

Node version:
```
$ npm --version
10.2.4

$ node --version
v21.2.0
```

Steps to replicate:
```
$ npm run build

> fthr-write@0.0.0 build
> tsc && vite build

vite v4.1.4 building for production...
transforming (116) node_modules/match-sorter/dist/match-sorter.esm.jsBrowserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
✓ 1617 modules transformed.
rendering chunks (3)...[vite-plugin-top-level-await] Fallback bindings does not support this interface yet.
error during build:
Error: Fallback bindings does not support this interface yet.
    at Compiler.<anonymous> (/home/mortilla/stuff/fthr-text/node_modules/@swc/core/index.js:119:23)
    at Generator.next (<anonymous>)
    at /home/mortilla/stuff/fthr-text/node_modules/@swc/core/index.js:34:71
    at new Promise (<anonymous>)
    at __awaiter (/home/mortilla/stuff/fthr-text/node_modules/@swc/core/index.js:30:12)
    at Compiler.parse (/home/mortilla/stuff/fthr-text/node_modules/@swc/core/index.js:115:16)
    at Object.parse (/home/mortilla/stuff/fthr-text/node_modules/@swc/core/index.js:320:21)
    at /home/mortilla/stuff/fthr-text/node_modules/vite-plugin-top-level-await/dist/bundle-info.js:33:19
    at Array.map (<anonymous>)
    at parseBundleAsts (/home/mortilla/stuff/fthr-text/node_modules/vite-plugin-top-level-await/dist/bundle-info.js:31:78)
```

**Comment by darrylschaefer** [comment]
Hi @mortilla, I added some optional dependences to support your platform. Could you test and see if it is building now?

**Comment by mortilla** [comment]
Thanks! Build works now, but calling `npm start`afterwards gives an error `npm ERR! Missing script: "start"`. Not sure if it something platform specific again. `npm run dev` works though.

**Comment by darrylschaefer** [comment]
No worries! It's a static application so there's no need to start a server unless you need one to serve the files, in which case you can use npm run dev. I updated the readme.
